### ISSUE TITLE
Missing scenario/in/route/most.commercial.rou.xml

### ISSUE THREAD

**Issue by crystalzyan** [lcodeca/MoSTScenario#2]
most.sumocfg references a file called "in/route/most.commercial.rou.xml", but it doesn't seem to exist in the repo. Calling "sumo -c 'most.sumocfg" with SUMO version 1.0 thus doesn't work, unless the reference to this file is removed. The error given is:

```
Error: The route file 'in/route/most.commercial.rou.xml' is not accessible.
Quitting (on error).
```

Is it valid to run this scenario without commercial.rou.xml?

**Comment by lcodeca** [comment]
Thanks for reporting. 
I forgot to add it to the repo.
It's done now.
