### ISSUE TITLE
invalid access from non-pedestrian lane

### ISSUE THREAD

**Issue by namdre** [lcodeca/MoSTScenario#4]
A recently added sumo error message exposes problems with the access definitions:
`Warning: Ignoring invalid access from non-pedestrian lane '153656_1' in busStop '131018'.`
(access should target the sidewalks if they exist).

**Comment by lcodeca** [comment]
Thank you, Jakob. This may be a major issue. I don't use accesses in the stop definition. 
When building it, I needed to decide where to put the stops. If the stop is not on the road (sidewalk), the vehicles have no access to it.  
Does this mean I need to add the access tag (to the sidewalk) to all my stops?

**Comment by namdre** [comment]
The stop should always be put on a vehicle lane.
An `<access>` definition is only ever needed if the whole edge disallows pedestrians (should be limited to railways). In this case, the access must be from a lane of another edge and this lane must allow pedestrians.
