### ISSUE TITLE
Error when running MoST with SUMO 1.20

### ISSUE THREAD

**Issue by KailinTong** [lcodeca/MoSTScenario#5]
Dear MoSTScenario developers,

thank you for offering this great traffic scenario. I tried to run it with SUMO 1.20 under Ubuntu 18.04.

An error displayed in the terminal, after Step #18425.50

`t9zLet/sumo-1.2.0+dfsg1/src/microsim/cfmodels/MSCFModel.cpp:776: double MSCFModel::maximumSafeStopSpeedEuler(double, double) const: Assertion `
`'h <= g + NUMERICAL_EPS' failed.`

Do you have some advice to solve this problem?

Thank you in advance!

Best regards,
Kailin

**Comment by lcodeca** [comment]
I just run the master version on Ubuntu 19.04. with 
```
Eclipse SUMO Version 1.2.0
 Build features: Linux-5.0.0-21-generic x86_64 GNU 8.3.0 Release Proj GUI GDAL FFmpeg GL2PS SWIG
```
and I cannot reproduce it.

Are you using the master or a release of MoST?
Have you compiled your version of sumo or it's from the PPA?

It seems strange to me that a sumo release would crash on an 'Assertion', because I get them only when running the debug version.

Regards,
Lara

**Comment by lcodeca** [comment]
Just for the records, with the (debug) version
```
Eclipse SUMO Version v1.3.1
 Build features: Linux-5.0.0-25-generic x86_64 GNU 8.3.0 Debug Proj GUI GDAL FFmpeg GL2PS SWIG
```
is not crashing, so the SUMO developers have already fixed the problem in SUMO.
I would use the latest SUMO version if I were you.

**Comment by KailinTong** [comment]
thank you @lcodeca,

I am using the master of the MoST.

my SUMO version from  the regular distribution of Ubuntu.
`Eclipse SUMO Version 1.2.0
 Build features: Linux-4.4.0-146-generic x86_64 GNU 7.4.0 None Proj GUI GDAL GL2PS
 Copyright (C) 2001-2019 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
`

I also tried with MoST release v0.6, the same error came out.

BR,
Kailin

**Comment by lcodeca** [comment]
The problem that you are seeing comes from an assertion in SUMO and from my tests, in the last version of SUMO, the behavior that generates the problem has been resolved.
If you need to use SUMO 1.2, you need to compile it yourself so the debug is disabled.
Otherwise, you need to use SUMO 1.3.1.
