### ISSUE TITLE
Exectuing MoSTS simulation in Sumo 1.3.1

### ISSUE THREAD

**Issue by coloal** [lcodeca/MoSTScenario#6]
I am executing the scenario in Sumo 1.3.1, just cloned the master. Is it posible to make a simulation like the ones shown in the videos? I mean with cars, lorries and more traffic? In my simulation are only (apparently) used buses and trains.

**Comment by lcodeca** [comment]
I just used 
`Eclipse SUMO Version 1.3.1
 Build features: Darwin-18.2.0 x86_64 Clang 10.0.0.10001044 Release Proj GUI`
with a fresh clone of the master, and I launched it with 
`sumo-gui scenario/most.sumocfg`
and I got this screenshot:
<img width="1210" alt="Screen Shot 2019-11-17 at 3 34 44 PM" src="https://user-images.githubusercontent.com/5700703/69009712-038fa280-0950-11ea-833b-b2cdb67b1f76.png">
I have people, cars and public transports.
