### ISSUE TITLE
MoSTS connections

### ISSUE THREAD

**Issue by coloal** [lcodeca/MoSTScenario#7]
Hello,
I am using the MoSTS scenario along with Sumo and Flow framework. I am having an issue when Flow tries to read the '*.net.xml' since it crashes when trying to read some connections defined in this file. The Flow code supposes that a connection that goes from a lane to an internal link, for example: 
` <connection from="-152476" to=":131254_w0" fromLane="0" toLane="0" dir="s" state="M"/>`
 should have an attribute 'via', but it hasn't. I have look for this restriction in sumo documentation but all I found is this: " it should be taken into account that a connection with an internal lane follows a special pattern. For example when lane 1_f_0 needs to be connected to 1_t_0 through 1_v_0, the following connection entries exist: [from=1_f_0, to=1_t_0 via=1_v_0] and [from=1_v_0 to=1_t_0]. If the latter is omitted, SUMO will not load the network. It will also not load if next to the necessary connections a connection [from=1_f_0 to=1_v_0] exists.", I don't know if this applies to the case exposed for the upper conection or it is just a bug in Flow code.
Thanks a lot,
Alberto

**Comment by lcodeca** [comment]
Hello,
I need to ask you what version of SUMO are you using. 
The last time I checked (https://berkeleyflow.readthedocs.io/en/latest/flow_setup.html) flows requires an old version of SUMO (v0_32_0~762) and MoST Scenario is probably not compatible with SUMO versions before the 1.0.
Regards,
Lara

**Comment by coloal** [comment]
I checked It and the last versiom compatible with flow is the 1.1.0 which I am using, and that's the MoSTS version I am using too.

**Comment by lcodeca** [comment]
I just re-launched https://github.com/lcodeca/MoSTScenario/releases/tag/v0.6 and it works with SUMO 1.1. I never had to deal with Flow, so I cannot help you there.
Do you have the same error without Flow involved? 
If so, can you paste the log? I can try to understand what's happening in that case, but as far as I can test it, MoST works as it should.

**Comment by coloal** [comment]
The version for sumo 1.1.0 is the v0.5, is'n it?

**Comment by lcodeca** [comment]
If you check the README.md you will see that v0.6 has been tested with SUMO 1.1 too.
Anyhow, I tried v0.5 and it's not giving me errors with SUMO 1.1.
